# Generated by Django 2.0.1 on 2018-02-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180217_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='email',
            new_name='mail',
        ),
    ]
