# Generated by Django 2.0.1 on 2018-02-19 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180217_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='assistant',
            name='apellidos',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='nombres',
            field=models.CharField(max_length=25),
        ),
    ]
